import React from 'react';

const pianoKeys = [
    { sharp: 'A0', flat: 'A0', midi: 21 },
    { sharp: 'A#0', flat: 'Bb0', midi: 22 },
    { sharp: 'B0', flat: 'B0', midi: 23 },
    { sharp: 'C1', flat: 'C1', midi: 24 },
    { sharp: 'C#1', flat: 'Db1', midi: 25 },
    { sharp: 'D1', flat: 'D1', midi: 26 },
    { sharp: 'D#1', flat: 'Eb1', midi: 27 },
    { sharp: 'E1', flat: 'E1', midi: 28 },
    { sharp: 'F1', flat: 'F1', midi: 29 },
    { sharp: 'F#1', flat: 'Gb1', midi: 30 },
    { sharp: 'G1', flat: 'G1', midi: 31 },
    { sharp: 'G#1', flat: 'Ab1', midi: 32 },
    { sharp: 'A1', flat: 'A1', midi: 33 },
    { sharp: 'A#1', flat: 'Bb1', midi: 34 },
    { sharp: 'B1', flat: 'B1', midi: 35 },
    { sharp: 'C2', flat: 'C2', midi: 36 },
    { sharp: 'C#2', flat: 'Db2', midi: 37 },
    { sharp: 'D2', flat: 'D2', midi: 38 },
    { sharp: 'D#2', flat: 'Eb2', midi: 39 },
    { sharp: 'E2', flat: 'E2', midi: 40 },
    { sharp: 'F2', flat: 'F2', midi: 41 },
    { sharp: 'F#2', flat: 'Gb2', midi: 42 },
    { sharp: 'G2', flat: 'G2', midi: 43 },
    { sharp: 'G#2', flat: 'Ab2', midi: 44 },
    { sharp: 'A2', flat: 'A2', midi: 45 },
    { sharp: 'A#2', flat: 'Bb2', midi: 46 },
    { sharp: 'B2', flat: 'B2', midi: 47 },
    { sharp: 'C3', flat: 'C3', midi: 48 },
    { sharp: 'C#3', flat: 'Db3', midi: 49 },
    { sharp: 'D3', flat: 'D3', midi: 50 },
    { sharp: 'D#3', flat: 'Eb3', midi: 51 },
    { sharp: 'E3', flat: 'E3', midi: 52 },
    { sharp: 'F3', flat: 'F3', midi: 53 },
    { sharp: 'F#3', flat: 'Gb3', midi: 54 },
    { sharp: 'G3', flat: 'G3', midi: 55 },
    { sharp: 'G#3', flat: 'Ab3', midi: 56 },
    { sharp: 'A3', flat: 'A3', midi: 57 },
    { sharp: 'A#3', flat: 'Bb3', midi: 58 },
    { sharp: 'B3', flat: 'B3', midi: 59 },
    { sharp: 'C4', flat: 'C4', midi: 60 },
    { sharp: 'C#4', flat: 'Db4', midi: 61 },
    { sharp: 'D4', flat: 'D4', midi: 62 },
    { sharp: 'D#4', flat: 'Eb4', midi: 63 },
    { sharp: 'E4', flat: 'E4', midi: 64 },
    { sharp: 'F4', flat: 'F4', midi: 65 },
    { sharp: 'F#4', flat: 'Gb4', midi: 66 },
    { sharp: 'G4', flat: 'G4', midi: 67 },
    { sharp: 'G#4', flat: 'Ab4', midi: 68 },
    { sharp: 'A4', flat: 'A4', midi: 69 },
    { sharp: 'A#4', flat: 'Bb4', midi: 70 },
    { sharp: 'B4', flat: 'B4', midi: 71 },
    { sharp: 'C5', flat: 'C5', midi: 72 },
    { sharp: 'C#5', flat: 'Db5', midi: 73 },
    { sharp: 'D5', flat: 'D5', midi: 74 },
    { sharp: 'D#5', flat: 'Eb5', midi: 75 },
    { sharp: 'E5', flat: 'E5', midi: 76 },
    { sharp: 'F5', flat: 'F5', midi: 77 },
    { sharp: 'F#5', flat: 'Gb5', midi: 78 },
    { sharp: 'G5', flat: 'G5', midi: 79 },
    { sharp: 'G#5', flat: 'Ab5', midi: 80 },
    { sharp: 'A5', flat: 'A5', midi: 81 },
    { sharp: 'A#5', flat: 'Bb5', midi: 82 },
    { sharp: 'B5', flat: 'B5', midi: 83 },
    { sharp: 'C6', flat: 'C6', midi: 84 },
    { sharp: 'C#6', flat: 'Db6', midi: 85 },
    { sharp: 'D6', flat: 'D6', midi: 86 },
    { sharp: 'D#6', flat: 'Eb6', midi: 87 },
    { sharp: 'E6', flat: 'E6', midi: 88 },
    { sharp: 'F6', flat: 'F6', midi: 89 },
    { sharp: 'F#6', flat: 'Gb6', midi: 90 },
    { sharp: 'G6', flat: 'G6', midi: 91 },
    { sharp: 'G#6', flat: 'Ab6', midi: 92 },
    { sharp: 'A6', flat: 'A6', midi: 93 },
    { sharp: 'A#6', flat: 'Bb6', midi: 94 },
    { sharp: 'B6', flat: 'B6', midi: 95 },
    { sharp: 'C7', flat: 'C7', midi: 96 },
    { sharp: 'C#7', flat: 'Db7', midi: 97 },
    { sharp: 'D7', flat: 'D7', midi: 98 },
    { sharp: 'D#7', flat: 'Eb7', midi: 99 },
    { sharp: 'E7', flat: 'E7', midi: 100 },
    { sharp: 'F7', flat: 'F7', midi: 101 },
    { sharp: 'F#7', flat: 'Gb7', midi: 102 },
    { sharp: 'G7', flat: 'G7', midi: 103 },
    { sharp: 'G#7', flat: 'Ab7', midi: 104 },
    { sharp: 'A7', flat: 'A7', midi: 105 },
    { sharp: 'A#7', flat: 'Bb7', midi: 106 },
    { sharp: 'B7', flat: 'B7', midi: 107 },
    { sharp: 'C8', flat: 'C8', midi: 108 }
  ];
  const generateNotation = (isSharp) => {
    return pianoKeys.reduce((map, key) => {
      map[key.midi] = isSharp ? key.sharp : key.flat;
      return map;
    }, {});
  };
  // Usage:
const PianoKeyMapper = ({ note, isSharp }) => {
    const notation = isSharp ? generateNotation(true) : generateNotation(false);
    return <span>{notation[note] || 'Unknown'}</span>;
  };
  
  export default PianoKeyMapper;
  